"""创建示例期刊数据"""
import json
from pathlib import Path

from src.journals.journal_model import Journal

# 创建示例计算机类期刊数据
SAMPLE_JOURNALS = [
    {
        "journal_id": "tpami",
        "journal_name": "IEEE TPAMI",
        "publisher": "IEEE",
        "subject_tags": ["cv", "ai"],
        "keywords": ["computer vision", "pattern recognition", "deep learning", "neural network"],
        "scope_text": "Computer vision and pattern recognition, including all aspects of image, video, and multidimensional signal processing",
        "oa_type": "subscription",
        "quartile": "Q1",
        "sqr_rank": 5,
        "impact_like_score": 24.0,
        "review_time": "6-12 months",
        "apc": 0,
        "target_paper_type": ["method", "experiment", "survey"],
        "submission_url": "https://mc.manuscriptcentral.com/tpami",
        "homepage_url": "https://www.computer.org/web/tpami",
    },
    {
        "journal_id": "tnnls",
        "journal_name": "IEEE TNNLS",
        "publisher": "IEEE",
        "subject_tags": ["ai", "nlp"],
        "keywords": ["neural network", "deep learning", "machine learning", "reinforcement learning"],
        "scope_text": "Neural networks, machine learning, deep learning, reinforcement learning, and related areas",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 10,
        "impact_like_score": 15.0,
        "review_time": "3-6 months",
        "apc": 2500,
        "target_paper_type": ["method", "experiment"],
        "submission_url": "https://mc.manuscriptcentral.com/tnnls",
        "homepage_url": "https://ieee-tnnls.org/",
    },
    {
        "journal_id": "kbs",
        "journal_name": "Knowledge-Based Systems",
        "publisher": "Elsevier",
        "subject_tags": ["ai", "se"],
        "keywords": ["knowledge-based systems", "expert systems", "knowledge representation", "reasoning"],
        "scope_text": "Knowledge-based systems, expert systems, knowledge representation, reasoning, neural networks",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 20,
        "impact_like_score": 8.0,
        "review_time": "3-5 months",
        "apc": 2400,
        "target_paper_type": ["method", "system", "experiment"],
        "submission_url": "https://www.editorialmanager.com/kbs",
        "homepage_url": "https://www.sciencedirect.com/journal/knowledge-based-systems",
    },
    {
        "journal_id": "information-fusion",
        "journal_name": "Information Fusion",
        "publisher": "Elsevier",
        "subject_tags": ["ai", "cv"],
        "keywords": ["information fusion", "multi-sensor", "pattern recognition", "machine learning"],
        "scope_text": "Information fusion, multi-sensor systems, pattern recognition, machine learning, computer vision",
        "oa_type": "subscription",
        "quartile": "Q1",
        "sqr_rank": 8,
        "impact_like_score": 14.0,
        "review_time": "4-6 months",
        "apc": 0,
        "target_paper_type": ["method", "experiment"],
        "submission_url": "https://www.editorialmanager.com/inffus",
        "homepage_url": "https://www.sciencedirect.com/journal/information-fusion",
    },
    {
        "journal_id": "ins",
        "journal_name": "Information Sciences",
        "publisher": "Elsevier",
        "subject_tags": ["ai", "nlp", "db"],
        "keywords": ["information sciences", "data mining", "knowledge discovery", "machine learning"],
        "scope_text": "Information sciences, data mining, knowledge discovery, machine learning, natural language processing",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 15,
        "impact_like_score": 8.5,
        "review_time": "3-5 months",
        "apc": 2800,
        "target_paper_type": ["method", "experiment"],
        "submission_url": "https://www.editorialmanager.com/ins",
        "homepage_url": "https://www.sciencedirect.com/journal/information-sciences",
    },
    {
        "journal_id": "pr",
        "journal_name": "Pattern Recognition",
        "publisher": "Elsevier",
        "subject_tags": ["cv", "ai"],
        "keywords": ["pattern recognition", "computer vision", "image processing", "machine learning"],
        "scope_text": "Pattern recognition, computer vision, image processing, machine learning, document analysis",
        "oa_type": "subscription",
        "quartile": "Q1",
        "sqr_rank": 25,
        "impact_like_score": 7.0,
        "review_time": "4-6 months",
        "apc": 0,
        "target_paper_type": ["method", "experiment", "survey"],
        "submission_url": "https://www.editorialmanager.com/pr",
        "homepage_url": "https://www.sciencedirect.com/journal/pattern-recognition",
    },
    {
        "journal_id": "nn",
        "journal_name": "Neural Networks",
        "publisher": "Elsevier",
        "subject_tags": ["ai", "nlp"],
        "keywords": ["neural networks", "deep learning", "reinforcement learning", "cognitive science"],
        "scope_text": "Neural networks, deep learning, reinforcement learning, cognitive science, brain modeling",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 12,
        "impact_like_score": 10.0,
        "review_time": "3-5 months",
        "apc": 3000,
        "target_paper_type": ["method", "experiment", "survey"],
        "submission_url": "https://www.editorialmanager.com/nnet",
        "homepage_url": "https://www.sciencedirect.com/journal/neural-networks",
    },
    {
        "journal_id": "jbi",
        "journal_name": "Journal of Biomedical Informatics",
        "publisher": "Elsevier",
        "subject_tags": ["ai", "se"],
        "keywords": ["biomedical informatics", "health informatics", "machine learning", "clinical data"],
        "scope_text": "Biomedical informatics, health informatics, machine learning in medicine, clinical data analysis",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 30,
        "impact_like_score": 5.0,
        "review_time": "3-4 months",
        "apc": 2600,
        "target_paper_type": ["method", "experiment", "system"],
        "submission_url": "https://www.editorialmanager.com/jbi",
        "homepage_url": "https://www.sciencedirect.com/journal/journal-of-biomedical-informatics",
    },
    {
        "journal_id": "expert-sys",
        "journal_name": "Expert Systems",
        "publisher": "Wiley",
        "subject_tags": ["ai", "se"],
        "keywords": ["expert systems", "knowledge-based systems", "intelligent systems", "decision support"],
        "scope_text": "Expert systems, knowledge-based systems, intelligent systems, decision support systems",
        "oa_type": "hybrid",
        "quartile": "Q2",
        "sqr_rank": 45,
        "impact_like_score": 4.0,
        "review_time": "3-5 months",
        "apc": 2200,
        "target_paper_type": ["method", "system", "experiment"],
        "submission_url": "https://onlinelibrary.wiley.com/journal/1099050x",
        "homepage_url": "https://onlinelibrary.wiley.com/journal/expert-systems",
    },
    {
        "journal_id": "ijcv",
        "journal_name": "International Journal of Computer Vision",
        "publisher": "Springer",
        "subject_tags": ["cv", "ai"],
        "keywords": ["computer vision", "image understanding", "visual recognition", "deep learning"],
        "scope_text": "Computer vision, image understanding, visual recognition, deep learning, 3D reconstruction",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 6,
        "impact_like_score": 18.0,
        "review_time": "6-9 months",
        "apc": 3690,
        "target_paper_type": ["method", "experiment"],
        "submission_url": "https://www.editorialmanager.com/ijcv",
        "homepage_url": "https://www.springer.com/journal/11263",
    },
    {
        "journal_id": "tcyb",
        "journal_name": "IEEE Transactions on Cybernetics",
        "publisher": "IEEE",
        "subject_tags": ["ai", "se"],
        "keywords": ["cybernetics", "systems biology", "neural networks", "robotics", "control systems"],
        "scope_text": "Cybernetics, systems biology, neural networks, robotics, intelligent control, optimization",
        "oa_type": "subscription",
        "quartile": "Q1",
        "sqr_rank": 18,
        "impact_like_score": 12.0,
        "review_time": "4-6 months",
        "apc": 0,
        "target_paper_type": ["method", "experiment", "system"],
        "submission_url": "https://mc.manuscriptcentral.com/tcyb",
        "homepage_url": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6224437",
    },
    {
        "journal_id": "tsmc-sys",
        "journal_name": "IEEE Transactions on Systems, Man, and Cybernetics: Systems",
        "publisher": "IEEE",
        "subject_tags": ["ai", "se", "network"],
        "keywords": ["systems engineering", "human-machine systems", "cybernetics", "decision making"],
        "scope_text": "Systems engineering, human-machine systems, cybernetics, decision making, complex systems",
        "oa_type": "subscription",
        "quartile": "Q1",
        "sqr_rank": 22,
        "impact_like_score": 9.0,
        "review_time": "4-6 months",
        "apc": 0,
        "target_paper_type": ["method", "system", "experiment"],
        "submission_url": "https://mc.manuscriptcentral.com/tsmc",
        "homepage_url": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6224437",
    },
    {
        "journal_id": "access",
        "journal_name": "IEEE Access",
        "publisher": "IEEE",
        "subject_tags": ["ai", "cv", "nlp", "se", "network", "security", "db", "theory"],
        "keywords": ["multidisciplinary", "open access", "all areas of engineering"],
        "scope_text": "Multidisciplinary open access journal covering all areas of engineering and science",
        "oa_type": "full_oa",
        "quartile": "Q1",
        "sqr_rank": 35,
        "impact_like_score": 5.0,
        "review_time": "2-3 months",
        "apc": 2500,
        "target_paper_type": ["method", "system", "experiment", "survey"],
        "submission_url": "https://mc.manuscriptcentral.com/ieeeaccess",
        "homepage_url": "https://ieeeaccess.ieee.org/",
    },
    {
        "journal_id": "neurocomputing",
        "journal_name": "Neurocomputing",
        "publisher": "Elsevier",
        "subject_tags": ["ai", "nlp"],
        "keywords": ["neural networks", "learning systems", "deep learning", "cognitive models"],
        "scope_text": "Neural networks, learning systems, deep learning, cognitive models, brain-machine interfaces",
        "oa_type": "hybrid",
        "quartile": "Q1",
        "sqr_rank": 28,
        "impact_like_score": 6.0,
        "review_time": "3-5 months",
        "apc": 2800,
        "target_paper_type": ["method", "experiment"],
        "submission_url": "https://www.editorialmanager.com/neurocom",
        "homepage_url": "https://www.sciencedirect.com/journal/neurocomputing",
    },
    {
        "journal_id": "pami",
        "journal_name": "IEEE Transactions on Pattern Analysis and Machine Intelligence",
        "publisher": "IEEE",
        "subject_tags": ["cv", "ai", "nlp"],
        "keywords": ["pattern analysis", "machine intelligence", "computer vision", "AI"],
        "scope_text": "Pattern analysis, machine intelligence, computer vision, natural language processing, AI",
        "oa_type": "subscription",
        "quartile": "Q1",
        "sqr_rank": 3,
        "impact_like_score": 30.0,
        "review_time": "6-12 months",
        "apc": 0,
        "target_paper_type": ["method", "experiment", "survey"],
        "submission_url": "https://mc.manuscriptcentral.com/pami",
        "homepage_url": "https://www.computer.org/web/tpami",
    },
    {
        "journal_id": "cse",
        "journal_name": "Computing",
        "publisher": "Springer",
        "subject_tags": ["se", "db", "theory"],
        "keywords": ["computer science", "software engineering", "algorithms", "distributed computing"],
        "scope_text": "Computer science, software engineering, algorithms, distributed computing, database systems",
        "oa_type": "hybrid",
        "quartile": "Q2",
        "sqr_rank": 50,
        "impact_like_score": 3.5,
        "review_time": "4-6 months",
        "apc": 2100,
        "target_paper_type": ["method", "system", "experiment"],
        "submission_url": "https://www.editorialmanager.com/computing",
        "homepage_url": "https://www.springer.com/journal/160",
    },
]


def create_sample_journals():
    """创建示例期刊数据"""
    journals = []
    for data in SAMPLE_JOURNALS:
        journal = Journal(**data)
        journal.build_profile()
        journals.append(journal)

    # 确保目录存在
    output_dir = Path("data/processed")
    output_dir.mkdir(parents=True, exist_ok=True)

    # 保存到 JSONL
    output_file = output_dir / "journals.jsonl"
    with open(output_file, "w", encoding="utf-8") as f:
        for journal in journals:
            f.write(json.dumps(journal.model_dump(), ensure_ascii=False) + "\n")

    print(f"Created {len(journals)} sample journals")
    print(f"Saved to: {output_file}")

    for j in journals:
        print(f"  - {j.journal_name} ({j.quartile}, {j.oa_type})")

    return journals


if __name__ == "__main__":
    create_sample_journals()